In [1]:
import os
from pathlib import Path
import pandas as pd
import re
from sklearn.model_selection import train_test_split

from torch.utils.data import Dataset
from PIL import Image
import torch

# Loading Data

In [2]:
DATA_ROOT = Path("Data")
BENIGN_DIR = DATA_ROOT / "benign"
MALIGNANT_DIR = DATA_ROOT / "malignant"

In [3]:
records = []
print(len(records))

0

In [4]:
# Load Benign Images
for img_path in BENIGN_DIR.glob("*.png"):
    print(img_path)
    records.append({
        "path": str(img_path),
        "filename": img_path.name,
        "label": 0,
        "label_name": "benign"
    })

print(len(records))

Data\benign\SOB_B_A-14-22549AB-100-001.png
Data\benign\SOB_B_A-14-22549AB-100-002.png
Data\benign\SOB_B_A-14-22549AB-100-003.png
Data\benign\SOB_B_A-14-22549AB-100-004.png
Data\benign\SOB_B_A-14-22549AB-100-005.png
Data\benign\SOB_B_A-14-22549AB-100-006.png
Data\benign\SOB_B_A-14-22549AB-100-007.png
Data\benign\SOB_B_A-14-22549AB-100-008.png
Data\benign\SOB_B_A-14-22549AB-100-009.png
Data\benign\SOB_B_A-14-22549AB-100-010.png
Data\benign\SOB_B_A-14-22549AB-100-011.png
Data\benign\SOB_B_A-14-22549AB-100-012.png
Data\benign\SOB_B_A-14-22549AB-100-013.png
Data\benign\SOB_B_A-14-22549AB-100-014.png
Data\benign\SOB_B_A-14-22549AB-100-015.png
Data\benign\SOB_B_A-14-22549AB-100-016.png
Data\benign\SOB_B_A-14-22549AB-100-017.png
Data\benign\SOB_B_A-14-22549AB-100-018.png
Data\benign\SOB_B_A-14-22549AB-100-019.png
Data\benign\SOB_B_A-14-22549AB-100-020.png
Data\benign\SOB_B_A-14-22549AB-100-021.png
Data\benign\SOB_B_A-14-22549AB-100-022.png
Data\benign\SOB_B_A-14-22549AB-100-023.png
Data\benign\SOB_B_A-14-22549AB-100-024.png
Data\benign\SOB_B_A-14-22549AB-100-025.png
Data\benign\SOB_B_A-14-22549AB-100-026.png
Data\benign\SOB_B_A-14-22549AB-100-027.png
Data\benign\SOB_B_A-14-22549AB-100-028.png
Data\benign\SOB_B_A-14-22549AB-100-029.png
Data\benign\SOB_B_A-14-22549AB-100-030.png
Data\benign\SOB_B_A-14-22549AB-200-001.png
Data\benign\SOB_B_A-14-22549AB-200-002.png
Data\benign\SOB_B_A-14-22549AB-200-003.png
Data\benign\SOB_B_A-14-22549AB-200-004.png
Data\benign\SOB_B_A-14-22549AB-200-005.png
Data\benign\SOB_B_A-14-22549AB-200-006.png
Data\benign\SOB_B_A-14-22549AB-200-007.png
Data\benign\SOB_B_A-14-22549AB-200-008.png
Data\benign\SOB_B_A-14-22549AB-200-009.png
Data\benign\SOB_B_A-14-22549AB-200-010.png
Data\benign\SOB_B_A-14-22549AB-200-011.png
Data\benign\SOB_B_A-14-22549AB-200-012.png
Data\benign\SOB_B_A-14-22549AB-200-013.png
Data\benign\SOB_B_A-14-22549AB-200-014.png
Data\benign\SOB_B_A-14-22549AB-200-015.png
Data\benign\SOB_B_A-14-22549AB-200-016.png
Data\benign\SOB_B_A-14-22549AB-200-017.png
Data\benign\SOB_B_A-14-22549AB-200-018.png
Data\benign\SOB_B_A-14-22549AB-200-019.png
Data\benign\SOB_B_A-14-22549AB-200-020.png
Data\benign\SOB_B_A-14-22549AB-200-021.png
Data\benign\SOB_B_A-14-22549AB-200-022.png
Data\benign\SOB_B_A-14-22549AB-200-023.png
Data\benign\SOB_B_A-14-22549AB-200-024.png
Data\benign\SOB_B_A-14-22549AB-200-025.png
Data\benign\SOB_B_A-14-22549AB-200-026.png
Data\benign\SOB_B_A-14-22549AB-200-027.png
Data\benign\SOB_B_A-14-22549AB-200-028.png
Data\benign\SOB_B_A-14-22549AB-200-029.png
Data\benign\SOB_B_A-14-22549AB-200-030.png
Data\benign\SOB_B_A-14-22549AB-200-031.png
Data\benign\SOB_B_A-14-22549AB-200-032.png
Data\benign\SOB_B_A-14-22549AB-40-001.png
Data\benign\SOB_B_A-14-22549AB-40-002.png
Data\benign\SOB_B_A-14-22549AB-40-003.png
Data\benign\SOB_B_A-14-22549AB-40-004.png
Data\benign\SOB_B_A-14-22549AB-40-005.png
Data\benign\SOB_B_A-14-22549AB-40-006.png
Data\benign\SOB_B_A-14-22549AB-40-007.png
Data\benign\SOB_B_A-14-22549AB-40-008.png
Data\benign\SOB_B_A-14-22549AB-40-009.png
Data\benign\SOB_B_A-14-22549AB-40-010.png
Data\benign\SOB_B_A-14-22549AB-40-011.png
Data\benign\SOB_B_A-14-22549AB-40-012.png
Data\benign\SOB_B_A-14-22549AB-40-013.png
Data\benign\SOB_B_A-14-22549AB-40-014.png
Data\benign\SOB_B_A-14-22549AB-40-015.png
Data\benign\SOB_B_A-14-22549AB-40-016.png
Data\benign\SOB_B_A-14-22549AB-40-017.png
Data\benign\SOB_B_A-14-22549AB-40-018.png
Data\benign\SOB_B_A-14-22549AB-40-019.png
Data\benign\SOB_B_A-14-22549AB-40-020.png
Data\benign\SOB_B_A-14-22549AB-40-021.png
Data\benign\SOB_B_A-14-22549AB-40-022.png
Data\benign\SOB_B_A-14-22549AB-40-023.png
Data\benign\SOB_B_A-14-22549AB-40-024.png
Data\benign\SOB_B_A-14-22549AB-40-025.png
Data\benign\SOB_B_A-14-22549AB-40-026.png
Data\benign\SOB_B_A-14-22549AB-40-027.png
Data\benign\SOB_B_A-14-22549AB-40-028.png
Data\benign\SOB_B_A-14-22549AB-40-029.png
Data\benign\SOB_B_A-14-22549AB-400-001.png
Data\benign\SOB_B_A-14-22549AB-400-002.png
Data\benign\SOB_B_A-14-22549AB-400-003.png
Data\benign\SOB_B_A-14-22549AB-400-004.png
Data\benign\SOB_B_A-14-22549AB-400-005.png
Data\benign\SOB_B_A-14-22549AB-400-006.png
Data\benign\SOB_B_A-14-22549AB-400-007.png
Data\benign\SOB_B_A-14-22549AB-400-008.png
Data\benign\SOB_B_A-14-22549AB-400-009.png
Data\benign\SOB_B_A-14-22549AB-400-010.png
Data\benign\SOB_B_A-14-22549AB-400-011.png
Data\benign\SOB_B_A-14-22549AB-400-012.png
Data\benign\SOB_B_A-14-22549AB-400-013.png
Data\benign\SOB_B_A-14-22549AB-400-014.png
Data\benign\SOB_B_A-14-22549AB-400-015.png
Data\benign\SOB_B_A-14-22549AB-400-016.png
Data\benign\SOB_B_A-14-22549AB-400-017.png
Data\benign\SOB_B_A-14-22549AB-400-018.png
Data\benign\SOB_B_A-14-22549AB-400-019.png
Data\benign\SOB_B_A-14-22549AB-400-020.png
Data\benign\SOB_B_A-14-22549AB-400-021.png
Data\benign\SOB_B_A-14-22549AB-400-022.png
Data\benign\SOB_B_A-14-22549AB-400-023.png
Data\benign\SOB_B_A-14-22549AB-400-024.png
Data\benign\SOB_B_A-14-22549AB-400-025.png
Data\benign\SOB_B_A-14-22549AB-400-026.png
Data\benign\SOB_B_A-14-22549AB-400-027.png
Data\benign\SOB_B_A-14-22549AB-400-028.png
Data\benign\SOB_B_A-14-22549AB-400-029.png
Data\benign\SOB_B_A-14-22549AB-400-030.png
Data\benign\SOB_B_A-14-22549CD-100-001.png
Data\benign\SOB_B_A-14-22549CD-100-002.png
Data\benign\SOB_B_A-14-22549CD-100-003.png
Data\benign\SOB_B_A-14-22549CD-100-004.png
Data\benign\SOB_B_A-14-22549CD-100-005.png
Data\benign\SOB_B_A-14-22549CD-100-006.png
Data\benign\SOB_B_A-14-22549CD-100-007.png
Data\benign\SOB_B_A-14-22549CD-100-008.png
Data\benign\SOB_B_A-14-22549CD-100-009.png
Data\benign\SOB_B_A-14-22549CD-100-010.png
Data\benign\SOB_B_A-14-22549CD-100-011.png
Data\benign\SOB_B_A-14-22549CD-100-012.png
Data\benign\SOB_B_A-14-22549CD-100-013.png
Data\benign\SOB_B_A-14-22549CD-100-014.png
Data\benign\SOB_B_A-14-22549CD-100-015.png
Data\benign\SOB_B_A-14-22549CD-100-016.png
Data\benign\SOB_B_A-14-22549CD-100-017.png
Data\benign\SOB_B_A-14-22549CD-100-018.png
Data\benign\SOB_B_A-14-22549CD-100-019.png
Data\benign\SOB_B_A-14-22549CD-100-020.png
Data\benign\SOB_B_A-14-22549CD-100-021.png
Data\benign\SOB_B_A-14-22549CD-100-022.png
Data\benign\SOB_B_A-14-22549CD-100-023.png
Data\benign\SOB_B_A-14-22549CD-100-024.png
Data\benign\SOB_B_A-14-22549CD-100-025.png
Data\benign\SOB_B_A-14-22549CD-100-026.png
Data\benign\SOB_B_A-14-22549CD-100-027.png
Data\benign\SOB_B_A-14-22549CD-100-028.png
Data\benign\SOB_B_A-14-22549CD-100-029.png
Data\benign\SOB_B_A-14-22549CD-100-030.png
Data\benign\SOB_B_A-14-22549CD-100-031.png
Data\benign\SOB_B_A-14-22549CD-100-032.png
Data\benign\SOB_B_A-14-22549CD-100-033.png
Data\benign\SOB_B_A-14-22549CD-100-034.png
Data\benign\SOB_B_A-14-22549CD-100-035.png
Data\benign\SOB_B_A-14-22549CD-100-036.png
Data\benign\SOB_B_A-14-22549CD-200-001.png
Data\benign\SOB_B_A-14-22549CD-200-002.png
Data\benign\SOB_B_A-14-22549CD-200-003.png
Data\benign\SOB_B_A-14-22549CD-200-004.png
Data\benign\SOB_B_A-14-22549CD-200-005.png
Data\benign\SOB_B_A-14-22549CD-200-006.png
Data\benign\SOB_B_A-14-22549CD-200-007.png
Data\benign\SOB_B_A-14-22549CD-200-008.png
Data\benign\SOB_B_A-14-22549CD-200-009.png
Data\benign\SOB_B_A-14-22549CD-200-010.png
Data\benign\SOB_B_A-14-22549CD-200-011.png
Data\benign\SOB_B_A-14-22549CD-200-012.png
Data\benign\SOB_B_A-14-22549CD-200-013.png
Data\benign\SOB_B_A-14-22549CD-200-014.png
Data\benign\SOB_B_A-14-22549CD-200-015.png
Data\benign\SOB_B_A-14-22549CD-200-016.png
Data\benign\SOB_B_A-14-22549CD-200-017.png
Data\benign\SOB_B_A-14-22549CD-200-018.png
Data\benign\SOB_B_A-14-22549CD-200-019.png
Data\benign\SOB_B_A-14-22549CD-200-020.png
Data\benign\SOB_B_A-14-22549CD-200-021.png
Data\benign\SOB_B_A-14-22549CD-200-022.png
Data\benign\SOB_B_A-14-22549CD-200-023.png
Data\benign\SOB_B_A-14-22549CD-200-024.png
Data\benign\SOB_B_A-14-22549CD-200-025.png
Data\benign\SOB_B_A-14-22549CD-200-026.png
Data\benign\SOB_B_A-14-22549CD-200-027.png
Data\benign\SOB_B_A-14-22549CD-200-028.png
Data\benign\SOB_B_A-14-22549CD-200-029.png
Data\benign\SOB_B_A-14-22549CD-200-030.png
Data\benign\SOB_B_A-14-22549CD-200-031.png
Data\benign\SOB_B_A-14-22549CD-40-001.png
Data\benign\SOB_B_A-14-22549CD-40-002.png
Data\benign\SOB_B_A-14-22549CD-40-003.png
Data\benign\SOB_B_A-14-22549CD-40-004.png
Data\benign\SOB_B_A-14-22549CD-40-005.png
Data\benign\SOB_B_A-14-22549CD-40-006.png
Data\benign\SOB_B_A-14-22549CD-40-007.png
Data\benign\SOB_B_A-14-22549CD-40-008.png
Data\benign\SOB_B_A-14-22549CD-40-009.png
Data\benign\SOB_B_A-14-22549CD-40-010.png
Data\benign\SOB_B_A-14-22549CD-40-011.png
Data\benign\SOB_B_A-14-22549CD-40-012.png
Data\benign\SOB_B_A-14-22549CD-40-013.png
Data\benign\SOB_B_A-14-22549CD-40-014.png
Data\benign\SOB_B_A-14-22549CD-40-015.png
Data\benign\SOB_B_A-14-22549CD-40-016.png
Data\benign\SOB_B_A-14-22549CD-40-017.png
Data\benign\SOB_B_A-14-22549CD-40-018.png
Data\benign\SOB_B_A-14-22549CD-40-019.png
Data\benign\SOB_B_A-14-22549CD-40-020.png
Data\benign\SOB_B_A-14-22549CD-40-021.png
Data\benign\SOB_B_A-14-22549CD-40-022.png
Data\benign\SOB_B_A-14-22549CD-40-023.png
Data\benign\SOB_B_A-14-22549CD-40-024.png
Data\benign\SOB_B_A-14-22549CD-40-025.png
Data\benign\SOB_B_A-14-22549CD-40-026.png
Data\benign\SOB_B_A-14-22549CD-40-027.png
Data\benign\SOB_B_A-14-22549CD-40-028.png
Data\benign\SOB_B_A-14-22549CD-40-029.png
Data\benign\SOB_B_A-14-22549CD-40-030.png
Data\benign\SOB_B_A-14-22549CD-40-031.png
Data\benign\SOB_B_A-14-22549CD-40-032.png
Data\benign\SOB_B_A-14-22549CD-40-033.png
Data\benign\SOB_B_A-14-22549CD-40-034.png
Data\benign\SOB_B_A-14-22549CD-40-035.png
Data\benign\SOB_B_A-14-22549CD-400-001.png
Data\benign\SOB_B_A-14-22549CD-400-002.png
Data\benign\SOB_B_A-14-22549CD-400-003.png
Data\benign\SOB_B_A-14-22549CD-400-004.png
Data\benign\SOB_B_A-14-22549CD-400-005.png
Data\benign\SOB_B_A-14-22549CD-400-006.png
Data\benign\SOB_B_A-14-22549CD-400-007.png
Data\benign\SOB_B_A-14-22549CD-400-008.png
Data\benign\SOB_B_A-14-22549CD-400-009.png
Data\benign\SOB_B_A-14-22549CD-400-010.png
Data\benign\SOB_B_A-14-22549CD-400-011.png
Data\benign\SOB_B_A-14-22549CD-400-012.png
Data\benign\SOB_B_A-14-22549CD-400-013.png
Data\benign\SOB_B_A-14-22549CD-400-014.png
Data\benign\SOB_B_A-14-22549CD-400-015.png
Data\benign\SOB_B_A-14-22549CD-400-016.png
Data\benign\SOB_B_A-14-22549CD-400-017.png
Data\benign\SOB_B_A-14-22549CD-400-018.png
Data\benign\SOB_B_A-14-22549CD-400-019.png
Data\benign\SOB_B_A-14-22549CD-400-020.png
Data\benign\SOB_B_A-14-22549CD-400-021.png
Data\benign\SOB_B_A-14-22549CD-400-022.png
Data\benign\SOB_B_A-14-22549CD-400-023.png
Data\benign\SOB_B_A-14-22549CD-400-024.png
Data\benign\SOB_B_A-14-22549CD-400-025.png
Data\benign\SOB_B_A-14-22549CD-400-026.png
Data\benign\SOB_B_A-14-22549CD-400-027.png
Data\benign\SOB_B_A-14-22549CD-400-028.png
Data\benign\SOB_B_A-14-22549CD-400-029.png
Data\benign\SOB_B_A-14-22549CD-400-030.png
Data\benign\SOB_B_A-14-22549G-100-001.png
Data\benign\SOB_B_A-14-22549G-100-002.png
Data\benign\SOB_B_A-14-22549G-100-003.png
Data\benign\SOB_B_A-14-22549G-100-004.png
Data\benign\SOB_B_A-14-22549G-100-005.png
Data\benign\SOB_B_A-14-22549G-100-006.png
Data\benign\SOB_B_A-14-22549G-100-007.png
Data\benign\SOB_B_A-14-22549G-100-008.png
Data\benign\SOB_B_A-14-22549G-100-009.png
Data\benign\SOB_B_A-14-22549G-100-010.png
Data\benign\SOB_B_A-14-22549G-100-011.png
Data\benign\SOB_B_A-14-22549G-100-012.png
Data\benign\SOB_B_A-14-22549G-100-013.png
Data\benign\SOB_B_A-14-22549G-100-014.png
Data\benign\SOB_B_A-14-22549G-100-015.png
Data\benign\SOB_B_A-14-22549G-100-016.png
Data\benign\SOB_B_A-14-22549G-100-017.png
Data\benign\SOB_B_A-14-22549G-100-018.png
Data\benign\SOB_B_A-14-22549G-100-019.png
Data\benign\SOB_B_A-14-22549G-100-020.png
Data\benign\SOB_B_A-14-22549G-100-021.png
Data\benign\SOB_B_A-14-22549G-100-022.png
Data\benign\SOB_B_A-14-22549G-100-023.png
Data\benign\SOB_B_A-14-22549G-100-024.png
Data\benign\SOB_B_A-14-22549G-100-025.png
Data\benign\SOB_B_A-14-22549G-100-026.png
Data\benign\SOB_B_A-14-22549G-100-027.png
Data\benign\SOB_B_A-14-22549G-100-028.png
Data\benign\SOB_B_A-14-22549G-100-029.png
Data\benign\SOB_B_A-14-22549G-100-030.png
Data\benign\SOB_B_A-14-22549G-100-031.png
Data\benign\SOB_B_A-14-22549G-100-032.png
Data\benign\SOB_B_A-14-22549G-100-033.png
Data\benign\SOB_B_A-14-22549G-100-034.png
Data\benign\SOB_B_A-14-22549G-200-001.png
Data\benign\SOB_B_A-14-22549G-200-002.png
Data\benign\SOB_B_A-14-22549G-200-003.png
Data\benign\SOB_B_A-14-22549G-200-004.png
Data\benign\SOB_B_A-14-22549G-200-005.png
Data\benign\SOB_B_A-14-22549G-200-006.png
Data\benign\SOB_B_A-14-22549G-200-007.png
Data\benign\SOB_B_A-14-22549G-200-008.png
Data\benign\SOB_B_A-14-22549G-200-009.png
Data\benign\SOB_B_A-14-22549G-200-010.png
Data\benign\SOB_B_A-14-22549G-200-011.png
Data\benign\SOB_B_A-14-22549G-200-012.png
Data\benign\SOB_B_A-14-22549G-200-013.png
Data\benign\SOB_B_A-14-22549G-200-014.png
Data\benign\SOB_B_A-14-22549G-200-015.png
Data\benign\SOB_B_A-14-22549G-200-016.png
Data\benign\SOB_B_A-14-22549G-200-017.png
Data\benign\SOB_B_A-14-22549G-200-018.png
Data\benign\SOB_B_A-14-22549G-200-019.png
Data\benign\SOB_B_A-14-22549G-200-020.png
Data\benign\SOB_B_A-14-22549G-200-021.png
Data\benign\SOB_B_A-14-22549G-200-022.png
Data\benign\SOB_B_A-14-22549G-200-023.png
Data\benign\SOB_B_A-14-22549G-200-024.png
Data\benign\SOB_B_A-14-22549G-200-025.png
Data\benign\SOB_B_A-14-22549G-200-026.png
Data\benign\SOB_B_A-14-22549G-200-027.png
Data\benign\SOB_B_A-14-22549G-200-028.png
Data\benign\SOB_B_A-14-22549G-200-029.png
Data\benign\SOB_B_A-14-22549G-200-030.png
Data\benign\SOB_B_A-14-22549G-200-031.png
Data\benign\SOB_B_A-14-22549G-200-032.png
Data\benign\SOB_B_A-14-22549G-40-001.png
Data\benign\SOB_B_A-14-22549G-40-002.png
Data\benign\SOB_B_A-14-22549G-40-003.png
Data\benign\SOB_B_A-14-22549G-40-004.png
Data\benign\SOB_B_A-14-22549G-40-005.png
Data\benign\SOB_B_A-14-22549G-40-006.png
Data\benign\SOB_B_A-14-22549G-40-007.png
Data\benign\SOB_B_A-14-22549G-40-008.png
Data\benign\SOB_B_A-14-22549G-40-009.png
Data\benign\SOB_B_A-14-22549G-40-010.png
Data\benign\SOB_B_A-14-22549G-40-011.png
Data\benign\SOB_B_A-14-22549G-40-012.png
Data\benign\SOB_B_A-14-22549G-40-013.png
Data\benign\SOB_B_A-14-22549G-40-014.png
Data\benign\SOB_B_A-14-22549G-40-015.png
Data\benign\SOB_B_A-14-22549G-40-016.png
Data\benign\SOB_B_A-14-22549G-40-017.png
Data\benign\SOB_B_A-14-22549G-40-018.png
Data\benign\SOB_B_A-14-22549G-40-019.png
Data\benign\SOB_B_A-14-22549G-40-020.png
Data\benign\SOB_B_A-14-22549G-40-021.png
Data\benign\SOB_B_A-14-22549G-40-022.png
Data\benign\SOB_B_A-14-22549G-40-023.png
Data\benign\SOB_B_A-14-22549G-40-024.png
Data\benign\SOB_B_A-14-22549G-40-025.png
Data\benign\SOB_B_A-14-22549G-40-026.png
Data\benign\SOB_B_A-14-22549G-40-027.png
Data\benign\SOB_B_A-14-22549G-40-028.png
Data\benign\SOB_B_A-14-22549G-40-029.png
Data\benign\SOB_B_A-14-22549G-40-030.png
Data\benign\SOB_B_A-14-22549G-40-031.png
Data\benign\SOB_B_A-14-22549G-40-032.png
Data\benign\SOB_B_A-14-22549G-40-033.png
Data\benign\SOB_B_A-14-22549G-40-034.png
Data\benign\SOB_B_A-14-22549G-40-035.png
Data\benign\SOB_B_A-14-22549G-400-001.png
Data\benign\SOB_B_A-14-22549G-400-002.png
Data\benign\SOB_B_A-14-22549G-400-003.png
Data\benign\SOB_B_A-14-22549G-400-004.png
Data\benign\SOB_B_A-14-22549G-400-005.png
Data\benign\SOB_B_A-14-22549G-400-006.png
Data\benign\SOB_B_A-14-22549G-400-007.png
Data\benign\SOB_B_A-14-22549G-400-008.png
Data\benign\SOB_B_A-14-22549G-400-009.png
Data\benign\SOB_B_A-14-22549G-400-010.png
Data\benign\SOB_B_A-14-22549G-400-011.png
Data\benign\SOB_B_A-14-22549G-400-012.png
Data\benign\SOB_B_A-14-22549G-400-013.png
Data\benign\SOB_B_A-14-22549G-400-014.png
Data\benign\SOB_B_A-14-22549G-400-015.png
Data\benign\SOB_B_A-14-22549G-400-016.png
Data\benign\SOB_B_A-14-22549G-400-017.png
Data\benign\SOB_B_A-14-22549G-400-018.png
Data\benign\SOB_B_A-14-22549G-400-019.png
Data\benign\SOB_B_A-14-22549G-400-020.png
Data\benign\SOB_B_A-14-22549G-400-021.png
Data\benign\SOB_B_A-14-22549G-400-022.png
Data\benign\SOB_B_A-14-22549G-400-023.png
Data\benign\SOB_B_A-14-22549G-400-024.png
Data\benign\SOB_B_A-14-22549G-400-025.png
Data\benign\SOB_B_A-14-22549G-400-026.png
Data\benign\SOB_B_A-14-22549G-400-027.png
Data\benign\SOB_B_A-14-22549G-400-028.png
Data\benign\SOB_B_A-14-22549G-400-029.png
Data\benign\SOB_B_A-14-29960CD-100-001.png
Data\benign\SOB_B_A-14-29960CD-100-002.png
Data\benign\SOB_B_A-14-29960CD-100-003.png
Data\benign\SOB_B_A-14-29960CD-100-004.png
Data\benign\SOB_B_A-14-29960CD-100-005.png
Data\benign\SOB_B_A-14-29960CD-100-006.png
Data\benign\SOB_B_A-14-29960CD-100-007.png
Data\benign\SOB_B_A-14-29960CD-100-008.png
Data\benign\SOB_B_A-14-29960CD-100-009.png
Data\benign\SOB_B_A-14-29960CD-100-010.png
Data\benign\SOB_B_A-14-29960CD-100-011.png
Data\benign\SOB_B_A-14-29960CD-100-012.png
Data\benign\SOB_B_A-14-29960CD-100-013.png
Data\benign\SOB_B_A-14-29960CD-200-001.png
Data\benign\SOB_B_A-14-29960CD-200-002.png
Data\benign\SOB_B_A-14-29960CD-200-003.png
Data\benign\SOB_B_A-14-29960CD-200-004.png
Data\benign\SOB_B_A-14-29960CD-200-005.png
Data\benign\SOB_B_A-14-29960CD-200-006.png
Data\benign\SOB_B_A-14-29960CD-200-007.png
Data\benign\SOB_B_A-14-29960CD-200-008.png
Data\benign\SOB_B_A-14-29960CD-200-009.png
Data\benign\SOB_B_A-14-29960CD-200-010.png
Data\benign\SOB_B_A-14-29960CD-200-011.png
Data\benign\SOB_B_A-14-29960CD-200-012.png
Data\benign\SOB_B_A-14-29960CD-200-013.png
Data\benign\SOB_B_A-14-29960CD-200-014.png
Data\benign\SOB_B_A-14-29960CD-200-015.png
Data\benign\SOB_B_A-14-29960CD-200-016.png
Data\benign\SOB_B_A-14-29960CD-40-001.png
Data\benign\SOB_B_A-14-29960CD-40-002.png
Data\benign\SOB_B_A-14-29960CD-40-003.png
Data\benign\SOB_B_A-14-29960CD-40-004.png
Data\benign\SOB_B_A-14-29960CD-40-005.png
Data\benign\SOB_B_A-14-29960CD-40-006.png
Data\benign\SOB_B_A-14-29960CD-40-007.png
Data\benign\SOB_B_A-14-29960CD-40-008.png
Data\benign\SOB_B_A-14-29960CD-40-009.png
Data\benign\SOB_B_A-14-29960CD-40-010.png
Data\benign\SOB_B_A-14-29960CD-40-011.png
Data\benign\SOB_B_A-14-29960CD-40-012.png
Data\benign\SOB_B_A-14-29960CD-40-013.png
Data\benign\SOB_B_A-14-29960CD-40-014.png
Data\benign\SOB_B_A-14-29960CD-40-015.png
Data\benign\SOB_B_A-14-29960CD-400-001.png
Data\benign\SOB_B_A-14-29960CD-400-002.png
Data\benign\SOB_B_A-14-29960CD-400-003.png
Data\benign\SOB_B_A-14-29960CD-400-004.png
Data\benign\SOB_B_A-14-29960CD-400-005.png
Data\benign\SOB_B_A-14-29960CD-400-006.png
Data\benign\SOB_B_A-14-29960CD-400-007.png
Data\benign\SOB_B_A-14-29960CD-400-008.png
Data\benign\SOB_B_A-14-29960CD-400-009.png
Data\benign\SOB_B_A-14-29960CD-400-010.png
Data\benign\SOB_B_A-14-29960CD-400-011.png
Data\benign\SOB_B_A-14-29960CD-400-012.png
Data\benign\SOB_B_A-14-29960CD-400-013.png
Data\benign\SOB_B_A-14-29960CD-400-014.png
Data\benign\SOB_B_A-14-29960CD-400-015.png
Data\benign\SOB_B_A-14-29960CD-400-016.png
Data\benign\SOB_B_A-14-29960CD-400-017.png
Data\benign\SOB_B_F-14-14134-100-001.png
Data\benign\SOB_B_F-14-14134-100-002.png
Data\benign\SOB_B_F-14-14134-100-003.png
Data\benign\SOB_B_F-14-14134-100-004.png
Data\benign\SOB_B_F-14-14134-100-005.png
Data\benign\SOB_B_F-14-14134-100-006.png
Data\benign\SOB_B_F-14-14134-100-007.png
Data\benign\SOB_B_F-14-14134-100-008.png
Data\benign\SOB_B_F-14-14134-100-009.png
Data\benign\SOB_B_F-14-14134-100-010.png
Data\benign\SOB_B_F-14-14134-100-011.png
Data\benign\SOB_B_F-14-14134-100-012.png
Data\benign\SOB_B_F-14-14134-100-013.png
Data\benign\SOB_B_F-14-14134-100-014.png
Data\benign\SOB_B_F-14-14134-100-015.png
Data\benign\SOB_B_F-14-14134-100-016.png
Data\benign\SOB_B_F-14-14134-100-017.png
Data\benign\SOB_B_F-14-14134-100-018.png
Data\benign\SOB_B_F-14-14134-100-019.png
Data\benign\SOB_B_F-14-14134-100-020.png
Data\benign\SOB_B_F-14-14134-100-021.png
Data\benign\SOB_B_F-14-14134-100-022.png
Data\benign\SOB_B_F-14-14134-100-023.png
Data\benign\SOB_B_F-14-14134-100-024.png
Data\benign\SOB_B_F-14-14134-100-025.png
Data\benign\SOB_B_F-14-14134-100-026.png
Data\benign\SOB_B_F-14-14134-100-027.png
Data\benign\SOB_B_F-14-14134-100-028.png

In [5]:
# Load Malignant Images
for img_path in MALIGNANT_DIR.glob("*.png"):
    print(img_path)
    records.append({
        "path": str(img_path),
        "filename": img_path.name,
        "label": 0,
        "label_name": "malignant"
    })

    print(len(records))

Data\malignant\SOB_M_DC-14-10926-100-001.png
2480
Data\malignant\SOB_M_DC-14-10926-100-002.png
2481
Data\malignant\SOB_M_DC-14-10926-100-003.png
2482
Data\malignant\SOB_M_DC-14-10926-100-004.png
2483
Data\malignant\SOB_M_DC-14-10926-100-005.png
2484
Data\malignant\SOB_M_DC-14-10926-100-006.png
2485
Data\malignant\SOB_M_DC-14-10926-100-007.png
2486
Data\malignant\SOB_M_DC-14-10926-100-008.png
2487
Data\malignant\SOB_M_DC-14-10926-100-009.png
2488
Data\malignant\SOB_M_DC-14-10926-100-010.png
2489
Data\malignant\SOB_M_DC-14-10926-200-001.png
2490
Data\malignant\SOB_M_DC-14-10926-200-002.png
2491
Data\malignant\SOB_M_DC-14-10926-200-003.png
2492
Data\malignant\SOB_M_DC-14-10926-200-004.png
2493
Data\malignant\SOB_M_DC-14-10926-200-005.png
2494
Data\malignant\SOB_M_DC-14-10926-200-006.png
2495
Data\malignant\SOB_M_DC-14-10926-200-007.png
2496
Data\malignant\SOB_M_DC-14-10926-200-008.png
2497
Data\malignant\SOB_M_DC-14-10926-200-009.png
2498
Data\malignant\SOB_M_DC-14-10926-40-001.png
2499
Data\malignant\SOB_M_DC-14-10926-40-002.png
2500
Data\malignant\SOB_M_DC-14-10926-40-003.png
2501
Data\malignant\SOB_M_DC-14-10926-40-004.png
2502
Data\malignant\SOB_M_DC-14-10926-40-005.png
2503
Data\malignant\SOB_M_DC-14-10926-40-006.png
2504
Data\malignant\SOB_M_DC-14-10926-40-007.png
2505
Data\malignant\SOB_M_DC-14-10926-40-008.png
2506
Data\malignant\SOB_M_DC-14-10926-40-009.png
2507
Data\malignant\SOB_M_DC-14-10926-40-010.png
2508
Data\malignant\SOB_M_DC-14-10926-40-011.png
2509
Data\malignant\SOB_M_DC-14-10926-400-001.png
2510
Data\malignant\SOB_M_DC-14-10926-400-002.png
2511
Data\malignant\SOB_M_DC-14-10926-400-003.png
2512
Data\malignant\SOB_M_DC-14-10926-400-004.png
2513
Data\malignant\SOB_M_DC-14-10926-400-005.png
2514
Data\malignant\SOB_M_DC-14-10926-400-006.png
2515
Data\malignant\SOB_M_DC-14-10926-400-007.png
2516
Data\malignant\SOB_M_DC-14-10926-400-008.png
2517
Data\malignant\SOB_M_DC-14-10926-400-009.png
2518
Data\malignant\SOB_M_DC-14-11031-100-001.png
2519
Data\malignant\SOB_M_DC-14-11031-100-002.png
2520
Data\malignant\SOB_M_DC-14-11031-100-003.png
2521
Data\malignant\SOB_M_DC-14-11031-100-004.png
2522
Data\malignant\SOB_M_DC-14-11031-100-005.png
2523
Data\malignant\SOB_M_DC-14-11031-100-006.png
2524
Data\malignant\SOB_M_DC-14-11031-100-007.png
2525
Data\malignant\SOB_M_DC-14-11031-100-008.png
2526
Data\malignant\SOB_M_DC-14-11031-100-009.png
2527
Data\malignant\SOB_M_DC-14-11031-100-010.png
2528
Data\malignant\SOB_M_DC-14-11031-100-011.png
2529
Data\malignant\SOB_M_DC-14-11031-100-012.png
2530
Data\malignant\SOB_M_DC-14-11031-100-013.png
2531
Data\malignant\SOB_M_DC-14-11031-100-014.png
2532
Data\malignant\SOB_M_DC-14-11031-100-015.png
2533
Data\malignant\SOB_M_DC-14-11031-100-016.png
2534
Data\malignant\SOB_M_DC-14-11031-100-017.png
2535
Data\malignant\SOB_M_DC-14-11031-200-001.png
2536
Data\malignant\SOB_M_DC-14-11031-200-002.png
2537
Data\malignant\SOB_M_DC-14-11031-200-003.png
2538
Data\malignant\SOB_M_DC-14-11031-200-004.png
2539
Data\malignant\SOB_M_DC-14-11031-200-005.png
2540
Data\malignant\SOB_M_DC-14-11031-200-006.png
2541
Data\malignant\SOB_M_DC-14-11031-200-007.png
2542
Data\malignant\SOB_M_DC-14-11031-200-008.png
2543
Data\malignant\SOB_M_DC-14-11031-200-009.png
2544
Data\malignant\SOB_M_DC-14-11031-200-010.png
2545
Data\malignant\SOB_M_DC-14-11031-200-011.png
2546
Data\malignant\SOB_M_DC-14-11031-200-012.png
2547
Data\malignant\SOB_M_DC-14-11031-200-013.png
2548
Data\malignant\SOB_M_DC-14-11031-200-014.png
2549
Data\malignant\SOB_M_DC-14-11031-40-001.png
2550
Data\malignant\SOB_M_DC-14-11031-40-002.png
2551
Data\malignant\SOB_M_DC-14-11031-40-003.png
2552
Data\malignant\SOB_M_DC-14-11031-40-004.png
2553
Data\malignant\SOB_M_DC-14-11031-40-005.png
2554
Data\malignant\SOB_M_DC-14-11031-40-006.png
2555
Data\malignant\SOB_M_DC-14-11031-40-007.png
2556
Data\malignant\SOB_M_DC-14-11031-40-008.png
2557
Data\malignant\SOB_M_DC-14-11031-40-009.png
2558
Data\malignant\SOB_M_DC-14-11031-40-010.png
2559
Data\malignant\SOB_M_DC-14-11031-40-011.png
2560
Data\malignant\SOB_M_DC-14-11031-40-012.png
2561
Data\malignant\SOB_M_DC-14-11031-40-013.png
2562
Data\malignant\SOB_M_DC-14-11031-40-014.png
2563
Data\malignant\SOB_M_DC-14-11031-400-001.png
2564
Data\malignant\SOB_M_DC-14-11031-400-002.png
2565
Data\malignant\SOB_M_DC-14-11031-400-003.png
2566
Data\malignant\SOB_M_DC-14-11031-400-004.png
2567
Data\malignant\SOB_M_DC-14-11031-400-005.png
2568
Data\malignant\SOB_M_DC-14-11031-400-006.png
2569
Data\malignant\SOB_M_DC-14-11031-400-007.png
2570
Data\malignant\SOB_M_DC-14-11031-400-008.png
2571
Data\malignant\SOB_M_DC-14-11031-400-009.png
2572
Data\malignant\SOB_M_DC-14-11031-400-010.png
2573
Data\malignant\SOB_M_DC-14-11031-400-011.png
2574
Data\malignant\SOB_M_DC-14-11031-400-012.png
2575
Data\malignant\SOB_M_DC-14-11031-400-013.png
2576
Data\malignant\SOB_M_DC-14-11031-400-014.png
2577
Data\malignant\SOB_M_DC-14-11031-400-015.png
2578
Data\malignant\SOB_M_DC-14-11520-100-001.png
2579
Data\malignant\SOB_M_DC-14-11520-100-002.png
2580
Data\malignant\SOB_M_DC-14-11520-100-003.png
2581
Data\malignant\SOB_M_DC-14-11520-100-004.png
2582
Data\malignant\SOB_M_DC-14-11520-100-005.png
2583
Data\malignant\SOB_M_DC-14-11520-100-006.png
2584
Data\malignant\SOB_M_DC-14-11520-100-007.png
2585
Data\malignant\SOB_M_DC-14-11520-100-008.png
2586
Data\malignant\SOB_M_DC-14-11520-100-009.png
2587
Data\malignant\SOB_M_DC-14-11520-100-010.png
2588
Data\malignant\SOB_M_DC-14-11520-100-011.png
2589
Data\malignant\SOB_M_DC-14-11520-100-012.png
2590
Data\malignant\SOB_M_DC-14-11520-100-013.png
2591
Data\malignant\SOB_M_DC-14-11520-100-014.png
2592
Data\malignant\SOB_M_DC-14-11520-100-015.png
2593
Data\malignant\SOB_M_DC-14-11520-100-016.png
2594
Data\malignant\SOB_M_DC-14-11520-100-017.png
2595
Data\malignant\SOB_M_DC-14-11520-100-018.png
2596
Data\malignant\SOB_M_DC-14-11520-100-019.png
2597
Data\malignant\SOB_M_DC-14-11520-100-020.png
2598
Data\malignant\SOB_M_DC-14-11520-100-021.png
2599
Data\malignant\SOB_M_DC-14-11520-100-022.png
2600
Data\malignant\SOB_M_DC-14-11520-100-023.png
2601
Data\malignant\SOB_M_DC-14-11520-100-024.png
2602
Data\malignant\SOB_M_DC-14-11520-100-025.png
2603
Data\malignant\SOB_M_DC-14-11520-100-026.png
2604
Data\malignant\SOB_M_DC-14-11520-200-001.png
2605
Data\malignant\SOB_M_DC-14-11520-200-002.png
2606
Data\malignant\SOB_M_DC-14-11520-200-003.png
2607
Data\malignant\SOB_M_DC-14-11520-200-004.png
2608
Data\malignant\SOB_M_DC-14-11520-200-005.png
2609
Data\malignant\SOB_M_DC-14-11520-200-006.png
2610
Data\malignant\SOB_M_DC-14-11520-200-007.png
2611
Data\malignant\SOB_M_DC-14-11520-200-008.png
2612
Data\malignant\SOB_M_DC-14-11520-200-009.png
2613
Data\malignant\SOB_M_DC-14-11520-200-010.png
2614
Data\malignant\SOB_M_DC-14-11520-200-011.png
2615
Data\malignant\SOB_M_DC-14-11520-200-012.png
2616
Data\malignant\SOB_M_DC-14-11520-200-013.png
2617
Data\malignant\SOB_M_DC-14-11520-200-014.png
2618
Data\malignant\SOB_M_DC-14-11520-200-015.png
2619
Data\malignant\SOB_M_DC-14-11520-200-016.png
2620
Data\malignant\SOB_M_DC-14-11520-200-017.png
2621
Data\malignant\SOB_M_DC-14-11520-200-018.png
2622
Data\malignant\SOB_M_DC-14-11520-200-019.png
2623
Data\malignant\SOB_M_DC-14-11520-200-020.png
2624
Data\malignant\SOB_M_DC-14-11520-200-021.png
2625
Data\malignant\SOB_M_DC-14-11520-200-022.png
2626
Data\malignant\SOB_M_DC-14-11520-200-023.png
2627
Data\malignant\SOB_M_DC-14-11520-200-024.png
2628
Data\malignant\SOB_M_DC-14-11520-40-001.png
2629
Data\malignant\SOB_M_DC-14-11520-40-002.png
2630
Data\malignant\SOB_M_DC-14-11520-40-003.png
2631
Data\malignant\SOB_M_DC-14-11520-40-004.png
2632
Data\malignant\SOB_M_DC-14-11520-40-005.png
2633
Data\malignant\SOB_M_DC-14-11520-40-006.png
2634
Data\malignant\SOB_M_DC-14-11520-40-007.png
2635
Data\malignant\SOB_M_DC-14-11520-40-008.png
2636
Data\malignant\SOB_M_DC-14-11520-40-009.png
2637
Data\malignant\SOB_M_DC-14-11520-40-010.png
2638
Data\malignant\SOB_M_DC-14-11520-40-011.png
2639
Data\malignant\SOB_M_DC-14-11520-40-012.png
2640
Data\malignant\SOB_M_DC-14-11520-40-013.png
2641
Data\malignant\SOB_M_DC-14-11520-40-014.png
2642
Data\malignant\SOB_M_DC-14-11520-40-015.png
2643
Data\malignant\SOB_M_DC-14-11520-40-016.png
2644
Data\malignant\SOB_M_DC-14-11520-40-017.png
2645
Data\malignant\SOB_M_DC-14-11520-40-018.png
2646
Data\malignant\SOB_M_DC-14-11520-40-019.png
2647
Data\malignant\SOB_M_DC-14-11520-40-020.png
2648
Data\malignant\SOB_M_DC-14-11520-40-021.png
2649
Data\malignant\SOB_M_DC-14-11520-40-022.png
2650
Data\malignant\SOB_M_DC-14-11520-40-023.png
2651
Data\malignant\SOB_M_DC-14-11520-40-024.png
2652
Data\malignant\SOB_M_DC-14-11520-40-025.png
2653
Data\malignant\SOB_M_DC-14-11520-400-001.png
2654
Data\malignant\SOB_M_DC-14-11520-400-002.png
2655
Data\malignant\SOB_M_DC-14-11520-400-003.png
2656
Data\malignant\SOB_M_DC-14-11520-400-004.png
2657
Data\malignant\SOB_M_DC-14-11520-400-005.png
2658
Data\malignant\SOB_M_DC-14-11520-400-006.png
2659
Data\malignant\SOB_M_DC-14-11520-400-007.png
2660
Data\malignant\SOB_M_DC-14-11520-400-008.png
2661
Data\malignant\SOB_M_DC-14-11520-400-009.png
2662
Data\malignant\SOB_M_DC-14-11520-400-010.png
2663
Data\malignant\SOB_M_DC-14-11520-400-011.png
2664
Data\malignant\SOB_M_DC-14-11520-400-012.png
2665
Data\malignant\SOB_M_DC-14-11520-400-013.png
2666
Data\malignant\SOB_M_DC-14-11520-400-014.png
2667
Data\malignant\SOB_M_DC-14-11520-400-015.png
2668
Data\malignant\SOB_M_DC-14-11520-400-016.png
2669
Data\malignant\SOB_M_DC-14-11520-400-017.png
2670
Data\malignant\SOB_M_DC-14-11520-400-018.png
2671
Data\malignant\SOB_M_DC-14-11520-400-019.png
2672
Data\malignant\SOB_M_DC-14-11520-400-020.png
2673
Data\malignant\SOB_M_DC-14-11520-400-021.png
2674
Data\malignant\SOB_M_DC-14-11520-400-022.png
2675
Data\malignant\SOB_M_DC-14-11520-400-023.png
2676
Data\malignant\SOB_M_DC-14-11951-100-001.png
2677
Data\malignant\SOB_M_DC-14-11951-100-002.png
2678
Data\malignant\SOB_M_DC-14-11951-100-003.png
2679
Data\malignant\SOB_M_DC-14-11951-100-004.png
2680
Data\malignant\SOB_M_DC-14-11951-100-005.png
2681
Data\malignant\SOB_M_DC-14-11951-100-006.png
2682
Data\malignant\SOB_M_DC-14-11951-100-007.png
2683
Data\malignant\SOB_M_DC-14-11951-100-008.png
2684
Data\malignant\SOB_M_DC-14-11951-100-009.png
2685
Data\malignant\SOB_M_DC-14-11951-100-010.png
2686
Data\malignant\SOB_M_DC-14-11951-100-011.png
2687
Data\malignant\SOB_M_DC-14-11951-100-012.png
2688
Data\malignant\SOB_M_DC-14-11951-100-013.png
2689
Data\malignant\SOB_M_DC-14-11951-100-014.png
2690
Data\malignant\SOB_M_DC-14-11951-100-015.png
2691
Data\malignant\SOB_M_DC-14-11951-100-016.png
2692
Data\malignant\SOB_M_DC-14-11951-100-017.png
2693
Data\malignant\SOB_M_DC-14-11951-100-018.png
2694
Data\malignant\SOB_M_DC-14-11951-100-019.png
2695
Data\malignant\SOB_M_DC-14-11951-100-020.png
2696
Data\malignant\SOB_M_DC-14-11951-100-021.png
2697
Data\malignant\SOB_M_DC-14-11951-100-022.png
2698
Data\malignant\SOB_M_DC-14-11951-100-023.png
2699
Data\malignant\SOB_M_DC-14-11951-100-024.png
2700
Data\malignant\SOB_M_DC-14-11951-100-025.png
2701
Data\malignant\SOB_M_DC-14-11951-200-001.png
2702
Data\malignant\SOB_M_DC-14-11951-200-002.png
2703
Data\malignant\SOB_M_DC-14-11951-200-003.png
2704
Data\malignant\SOB_M_DC-14-11951-200-004.png
2705
Data\malignant\SOB_M_DC-14-11951-200-005.png
2706
Data\malignant\SOB_M_DC-14-11951-200-006.png
2707
Data\malignant\SOB_M_DC-14-11951-200-007.png
2708
Data\malignant\SOB_M_DC-14-11951-200-008.png
2709
Data\malignant\SOB_M_DC-14-11951-200-009.png
2710
Data\malignant\SOB_M_DC-14-11951-200-010.png
2711
Data\malignant\SOB_M_DC-14-11951-200-011.png
2712
Data\malignant\SOB_M_DC-14-11951-200-012.png
2713
Data\malignant\SOB_M_DC-14-11951-200-013.png
2714
Data\malignant\SOB_M_DC-14-11951-200-014.png
2715
Data\malignant\SOB_M_DC-14-11951-200-015.png
2716
Data\malignant\SOB_M_DC-14-11951-200-016.png
2717
Data\malignant\SOB_M_DC-14-11951-200-017.png
2718
Data\malignant\SOB_M_DC-14-11951-200-018.png
2719
Data\malignant\SOB_M_DC-14-11951-200-019.png
2720
Data\malignant\SOB_M_DC-14-11951-200-020.png
2721
Data\malignant\SOB_M_DC-14-11951-200-021.png
2722
Data\malignant\SOB_M_DC-14-11951-200-022.png
2723
Data\malignant\SOB_M_DC-14-11951-200-023.png
2724
Data\malignant\SOB_M_DC-14-11951-200-024.png
2725
Data\malignant\SOB_M_DC-14-11951-200-025.png
2726
Data\malignant\SOB_M_DC-14-11951-200-026.png
2727
Data\malignant\SOB_M_DC-14-11951-200-027.png
2728
Data\malignant\SOB_M_DC-14-11951-200-028.png
2729
Data\malignant\SOB_M_DC-14-11951-40-001.png
2730
Data\malignant\SOB_M_DC-14-11951-40-002.png
2731
Data\malignant\SOB_M_DC-14-11951-40-003.png
2732
Data\malignant\SOB_M_DC-14-11951-40-004.png
2733
Data\malignant\SOB_M_DC-14-11951-40-005.png
2734
Data\malignant\SOB_M_DC-14-11951-40-006.png
2735
Data\malignant\SOB_M_DC-14-11951-40-007.png
2736
Data\malignant\SOB_M_DC-14-11951-40-008.png
2737
Data\malignant\SOB_M_DC-14-11951-40-009.png
2738
Data\malignant\SOB_M_DC-14-11951-40-010.png
2739
Data\malignant\SOB_M_DC-14-11951-40-011.png
2740
Data\malignant\SOB_M_DC-14-11951-40-012.png
2741
Data\malignant\SOB_M_DC-14-11951-40-013.png
2742
Data\malignant\SOB_M_DC-14-11951-40-014.png
2743
Data\malignant\SOB_M_DC-14-11951-40-015.png
2744
Data\malignant\SOB_M_DC-14-11951-40-016.png
2745
Data\malignant\SOB_M_DC-14-11951-40-017.png
2746
Data\malignant\SOB_M_DC-14-11951-40-018.png
2747
Data\malignant\SOB_M_DC-14-11951-40-019.png
2748
Data\malignant\SOB_M_DC-14-11951-40-020.png
2749
Data\malignant\SOB_M_DC-14-11951-40-021.png
2750
Data\malignant\SOB_M_DC-14-11951-40-022.png
2751
Data\malignant\SOB_M_DC-14-11951-40-023.png
2752
Data\malignant\SOB_M_DC-14-11951-40-024.png
2753
Data\malignant\SOB_M_DC-14-11951-40-025.png
2754
Data\malignant\SOB_M_DC-14-11951-40-026.png
2755
Data\malignant\SOB_M_DC-14-11951-40-027.png
2756
Data\malignant\SOB_M_DC-14-11951-400-001.png
2757
Data\malignant\SOB_M_DC-14-11951-400-002.png
2758
Data\malignant\SOB_M_DC-14-11951-400-003.png
2759
Data\malignant\SOB_M_DC-14-11951-400-004.png
2760
Data\malignant\SOB_M_DC-14-11951-400-005.png
2761
Data\malignant\SOB_M_DC-14-11951-400-006.png
2762
Data\malignant\SOB_M_DC-14-11951-400-007.png
2763
Data\malignant\SOB_M_DC-14-11951-400-008.png
2764
Data\malignant\SOB_M_DC-14-11951-400-009.png
2765
Data\malignant\SOB_M_DC-14-11951-400-010.png
2766
Data\malignant\SOB_M_DC-14-11951-400-011.png
2767
Data\malignant\SOB_M_DC-14-11951-400-012.png
2768
Data\malignant\SOB_M_DC-14-11951-400-013.png
2769
Data\malignant\SOB_M_DC-14-11951-400-014.png
2770
Data\malignant\SOB_M_DC-14-11951-400-015.png
2771
Data\malignant\SOB_M_DC-14-11951-400-016.png
2772
Data\malignant\SOB_M_DC-14-11951-400-017.png
2773
Data\malignant\SOB_M_DC-14-11951-400-018.png
2774
Data\malignant\SOB_M_DC-14-11951-400-019.png
2775
Data\malignant\SOB_M_DC-14-11951-400-020.png
2776
Data\malignant\SOB_M_DC-14-12312-100-001.png
2777
Data\malignant\SOB_M_DC-14-12312-100-002.png
2778
Data\malignant\SOB_M_DC-14-12312-100-003.png
2779
Data\malignant\SOB_M_DC-14-12312-100-004.png
2780
Data\malignant\SOB_M_DC-14-12312-100-005.png
2781
Data\malignant\SOB_M_DC-14-12312-100-006.png
2782
Data\malignant\SOB_M_DC-14-12312-100-007.png
2783
Data\malignant\SOB_M_DC-14-12312-100-008.png
2784
Data\malignant\SOB_M_DC-14-12312-100-009.png
2785
Data\malignant\SOB_M_DC-14-12312-100-010.png
2786
Data\malignant\SOB_M_DC-14-12312-100-011.png
2787
Data\malignant\SOB_M_DC-14-12312-100-012.png
2788
Data\malignant\SOB_M_DC-14-12312-100-013.png
2789
Data\malignant\SOB_M_DC-14-12312-100-014.png
2790
Data\malignant\SOB_M_DC-14-12312-100-015.png
2791
Data\malignant\SOB_M_DC-14-12312-100-016.png
2792
Data\malignant\SOB_M_DC-14-12312-100-017.png
2793
Data\malignant\SOB_M_DC-14-12312-100-018.png
2794
Data\malignant\SOB_M_DC-14-12312-100-019.png
2795
Data\malignant\SOB_M_DC-14-12312-100-020.png
2796
Data\malignant\SOB_M_DC-14-12312-100-021.png
2797
Data\malignant\SOB_M_DC-14-12312-100-022.png
2798
Data\malignant\SOB_M_DC-14-12312-100-023.png
2799
Data\malignant\SOB_M_DC-14-12312-100-024.png
2800
Data\malignant\SOB_M_DC-14-12312-100-025.png
2801
Data\malignant\SOB_M_DC-14-12312-100-026.png
2802
Data\malignant\SOB_M_DC-14-12312-100-027.png
2803
Data\malignant\SOB_M_DC-14-12312-100-028.png
2804
Data\malignant\SOB_M_DC-14-12312-100-029.png
2805
Data\malignant\SOB_M_DC-14-12312-100-030.png
2806
Data\malignant\SOB_M_DC-14-12312-100-031.png
2807
Data\malignant\SOB_M_DC-14-12312-100-032.png
2808
Data\malignant\SOB_M_DC-14-12312-100-033.png
2809
Data\malignant\SOB_M_DC-14-12312-100-034.png
2810
Data\malignant\SOB_M_DC-14-12312-100-035.png
2811
Data\malignant\SOB_M_DC-14-12312-100-036.png
2812
Data\malignant\SOB_M_DC-14-12312-100-037.png
2813
Data\malignant\SOB_M_DC-14-12312-100-038.png
2814
Data\malignant\SOB_M_DC-14-12312-100-039.png
2815
Data\malignant\SOB_M_DC-14-12312-100-040.png
2816
Data\malignant\SOB_M_DC-14-12312-100-041.png
2817
Data\malignant\SOB_M_DC-14-12312-200-001.png
2818
Data\malignant\SOB_M_DC-14-12312-200-002.png
2819
Data\malignant\SOB_M_DC-14-12312-200-003.png
2820
Data\malignant\SOB_M_DC-14-12312-200-004.png
2821
Data\malignant\SOB_M_DC-14-12312-200-005.png
2822
Data\malignant\SOB_M_DC-14-12312-200-006.png
2823
Data\malignant\SOB_M_DC-14-12312-200-007.png
2824
Data\malignant\SOB_M_DC-14-12312-200-008.png
2825
Data\malignant\SOB_M_DC-14-12312-200-009.png
2826
Data\malignant\SOB_M_DC-14-12312-200-010.png
2827
Data\malignant\SOB_M_DC-14-12312-200-011.png
2828
Data\malignant\SOB_M_DC-14-12312-200-012.png
2829
Data\malignant\SOB_M_DC-14-12312-200-013.png
2830
Data\malignant\SOB_M_DC-14-12312-200-014.png
2831
Data\malignant\SOB_M_DC-14-12312-200-015.png
2832
Data\malignant\SOB_M_DC-14-12312-200-016.png
2833
Data\malignant\SOB_M_DC-14-12312-200-017.png
2834
Data\malignant\SOB_M_DC-14-12312-200-018.png
2835
Data\malignant\SOB_M_DC-14-12312-200-019.png
2836
Data\malignant\SOB_M_DC-14-12312-200-020.png
2837
Data\malignant\SOB_M_DC-14-12312-200-021.png
2838
Data\malignant\SOB_M_DC-14-12312-200-022.png
2839
Data\malignant\SOB_M_DC-14-12312-200-023.png
2840
Data\malignant\SOB_M_DC-14-12312-200-024.png
2841
Data\malignant\SOB_M_DC-14-12312-200-025.png
2842
Data\malignant\SOB_M_DC-14-12312-200-026.png
2843
Data\malignant\SOB_M_DC-14-12312-200-027.png
2844
Data\malignant\SOB_M_DC-14-12312-200-028.png
2845
Data\malignant\SOB_M_DC-14-12312-200-029.png
2846
Data\malignant\SOB_M_DC-14-12312-200-030.png
2847
Data\malignant\SOB_M_DC-14-12312-200-031.png
2848
Data\malignant\SOB_M_DC-14-12312-200-032.png
2849
Data\malignant\SOB_M_DC-14-12312-200-033.png
2850
Data\malignant\SOB_M_DC-14-12312-200-034.png
2851
Data\malignant\SOB_M_DC-14-12312-200-035.png
2852
Data\malignant\SOB_M_DC-14-12312-40-001.png
2853
Data\malignant\SOB_M_DC-14-12312-40-002.png
2854
Data\malignant\SOB_M_DC-14-12312-40-003.png
2855
Data\malignant\SOB_M_DC-14-12312-40-004.png
2856
Data\malignant\SOB_M_DC-14-12312-40-005.png
2857
Data\malignant\SOB_M_DC-14-12312-40-006.png
2858
Data\malignant\SOB_M_DC-14-12312-40-007.png
2859
Data\malignant\SOB_M_DC-14-12312-40-008.png
2860
Data\malignant\SOB_M_DC-14-12312-40-009.png
2861
Data\malignant\SOB_M_DC-14-12312-40-010.png
2862
Data\malignant\SOB_M_DC-14-12312-40-011.png
2863
Data\malignant\SOB_M_DC-14-12312-40-012.png
2864
Data\malignant\SOB_M_DC-14-12312-40-013.png
2865
Data\malignant\SOB_M_DC-14-12312-40-014.png
2866
Data\malignant\SOB_M_DC-14-12312-40-015.png
2867
Data\malignant\SOB_M_DC-14-12312-40-016.png
2868
Data\malignant\SOB_M_DC-14-12312-40-017.png
2869
Data\malignant\SOB_M_DC-14-12312-40-018.png
2870
Data\malignant\SOB_M_DC-14-12312-40-019.png
2871
Data\malignant\SOB_M_DC-14-12312-40-020.png
2872
Data\malignant\SOB_M_DC-14-12312-40-021.png
2873
Data\malignant\SOB_M_DC-14-12312-40-022.png
2874
Data\malignant\SOB_M_DC-14-12312-40-023.png
2875
Data\malignant\SOB_M_DC-14-12312-40-024.png
2876
Data\malignant\SOB_M_DC-14-12312-40-025.png
2877
Data\malignant\SOB_M_DC-14-12312-40-026.png
2878
Data\malignant\SOB_M_DC-14-12312-40-027.png
2879
Data\malignant\SOB_M_DC-14-12312-40-028.png
2880
Data\malignant\SOB_M_DC-14-12312-40-029.png
2881

In [6]:
# Convert to df
df = pd.DataFrame(records)

In [7]:
df

,path,filename,label,label_name
0,Data\benign\SOB_B_A-14-22549AB-100-001.png,SOB_B_A-14-22549AB-100-001.png,0,benign
1,Data\benign\SOB_B_A-14-22549AB-100-002.png,SOB_B_A-14-22549AB-100-002.png,0,benign
2,Data\benign\SOB_B_A-14-22549AB-100-003.png,SOB_B_A-14-22549AB-100-003.png,0,benign
3,Data\benign\SOB_B_A-14-22549AB-100-004.png,SOB_B_A-14-22549AB-100-004.png,0,benign
4,Data\benign\SOB_B_A-14-22549AB-100-005.png,SOB_B_A-14-22549AB-100-005.png,0,benign
...,...,...,...,...
7778,Data\malignant\SOB_M_PC-15-190EF-400-011.png,SOB_M_PC-15-190EF-400-011.png,0,malignant
7779,Data\malignant\SOB_M_PC-15-190EF-400-012.png,SOB_M_PC-15-190EF-400-012.png,0,malignant
7780,Data\malignant\SOB_M_PC-15-190EF-400-013.png,SOB_M_PC-15-190EF-400-013.png,0,malignant
7781,Data\malignant\SOB_M_PC-15-190EF-400-014.png,SOB_M_PC-15-190EF-400-014.png,0,malignant
7782,Data\malignant\SOB_M_PC-15-190EF-400-015.png,SOB_M_PC-15-190EF-400-015.png,0,malignant

# Extracting patient ID

In [8]:
def extract_patient_id(filename):
    """
    Extract patient ID from filename.
    Example: SOB_B_A-14-22549AB-40-011.png → 14-22549AB
    """

    # Remove the .png extension
    name = filename.replace(".png","")

    # Pattern: SOB_[B/M]_[TYPE]-[YEAR]-[SLIDE]-[MAG]-[SEQ]
    match = re.search(r"SOB_[BM]_[A-Z]+-(\d+-[A-Z0-9]+)-\d+-\d", name)

    if match:
        return match.group(1)
    else: 
        return None

In [9]:
# Apply the function to every filename
df['patient_id'] = df['filename'].apply(extract_patient_id)

In [10]:
df = df[['patient_id', 'filename', 'label', 'label_name', 'path']]

In [11]:
df.tail(5)

,patient_id,filename,label,label_name,path
7778,15-190EF,SOB_M_PC-15-190EF-400-011.png,0,malignant,Data\malignant\SOB_M_PC-15-190EF-400-011.png
7779,15-190EF,SOB_M_PC-15-190EF-400-012.png,0,malignant,Data\malignant\SOB_M_PC-15-190EF-400-012.png
7780,15-190EF,SOB_M_PC-15-190EF-400-013.png,0,malignant,Data\malignant\SOB_M_PC-15-190EF-400-013.png
7781,15-190EF,SOB_M_PC-15-190EF-400-014.png,0,malignant,Data\malignant\SOB_M_PC-15-190EF-400-014.png
7782,15-190EF,SOB_M_PC-15-190EF-400-015.png,0,malignant,Data\malignant\SOB_M_PC-15-190EF-400-015.png

In [12]:
print("Number of images with missing patient_id:", df["patient_id"].isna().sum())
print("\nExample of extracted patient IDs:")
print(df[["patient_id", "filename"]].head(10))

Number of images with missing patient_id: 0

Example of extracted patient IDs:
   patient_id                        filename
0  14-22549AB  SOB_B_A-14-22549AB-100-001.png
1  14-22549AB  SOB_B_A-14-22549AB-100-002.png
2  14-22549AB  SOB_B_A-14-22549AB-100-003.png
3  14-22549AB  SOB_B_A-14-22549AB-100-004.png
4  14-22549AB  SOB_B_A-14-22549AB-100-005.png
5  14-22549AB  SOB_B_A-14-22549AB-100-006.png
6  14-22549AB  SOB_B_A-14-22549AB-100-007.png
7  14-22549AB  SOB_B_A-14-22549AB-100-008.png
8  14-22549AB  SOB_B_A-14-22549AB-100-009.png
9  14-22549AB  SOB_B_A-14-22549AB-100-010.png

# QuickEDA

In [13]:
print("Total unique patients:", df["patient_id"].nunique())

print("\nNumber of patients per class:")
print(df.groupby("label_name")["patient_id"].nunique())

print("\nAverage number of images per patient:")
print(df.groupby("patient_id").size().mean())

print("\nImages per patient (summary):")
print(df.groupby("patient_id").size().describe())

Total unique patients: 81

Number of patients per class:
label_name
benign       24
malignant    57
Name: patient_id, dtype: int64

Average number of images per patient:
96.08641975308642

Images per patient (summary):
count     81.000000
mean      96.086420
std       38.256763
min       38.000000
25%       64.000000
50%       90.000000
75%      125.000000
max      235.000000
dtype: float64

# Patient-level df

In [14]:
df_patient=(
    df.groupby("patient_id")
      .agg(
          label=("label", "first"),
          label_name=("label_name", "first"),
          n_images=("filename", "count")
      )
      .reset_index()
)

print(df_patient.head(5))
print(df_patient.tail(5))
print(f"Total patient: {len(df_patient)}")
print(df_patient["label_name"].value_counts())

  patient_id  label label_name  n_images
0   14-10147      0  malignant        64
1   14-10926      0  malignant        39
2   14-11031      0  malignant        60
3   14-11520      0  malignant        98
4   14-11951      0  malignant       100
   patient_id  label label_name  n_images
76    14-8168      0  malignant        38
77    14-9133      0     benign       126
78    14-9146      0  malignant        90
79    14-9461      0  malignant       155
80   15-190EF      0  malignant        65
Total patient: 81
label_name
malignant    57
benign       24
Name: count, dtype: int64

# Patient-level Split

In [15]:
df_patient=(
    df.groupby("patient_id")
      .agg(
          label=("label", "first"),
          label_name=("label_name", "first"),
          n_image=("filename", "count")
      )
      .reset_index()
)

print(df_patient.head(5))
print(df_patient.tail(5))

  patient_id  label label_name  n_image
0   14-10147      0  malignant       64
1   14-10926      0  malignant       39
2   14-11031      0  malignant       60
3   14-11520      0  malignant       98
4   14-11951      0  malignant      100
   patient_id  label label_name  n_image
76    14-8168      0  malignant       38
77    14-9133      0     benign      126
78    14-9146      0  malignant       90
79    14-9461      0  malignant      155
80   15-190EF      0  malignant       65

# Patient-level Split

In [16]:
train, temp = train_test_split(
    df_patient,
    test_size= 0.25,
    stratify= df_patient["label"],
    random_state=42
)

val, test = train_test_split(
    temp,
    test_size=0.60,              # 60% of 25% = 15%
    stratify=temp["label"],
    random_state=42
)

print(f"Train patients: {len(train)}")
print(f"Val patients:   {len(val)}")
print(f"Test patients:  {len(test)}")

Train patients: 60
Val patients:   8
Test patients:  13

# Expand back to images

In [17]:
train=df[df['patient_id'].isin(train['patient_id'])].reset_index(drop=True)
val=df[df['patient_id'].isin(val['patient_id'])].reset_index(drop=True)
test=df[df['patient_id'].isin(test['patient_id'])].reset_index(drop=True)

print(f"Train patients: {len(train)}")
print(f"Val patients:   {len(val)}")
print(f"Test patients:  {len(test)}")

Train patients: 5842
Val patients:   864
Test patients:  1077

In [18]:
# Converting patient IDs into sets
train_ids = set(train['patient_id'])
val_ids = set(val['patient_id'])
test_ids = set(test['patient_id'])

# Check Overlap
print(f"Overlap Train Val: {len(train_ids & val_ids)}")
print(f"Overlap Test Val: {len(test_ids & val_ids)}")
print(f"Overlap Train Test: {len(train_ids & test_ids)}")

Overlap Train Val: 0
Overlap Test Val: 0
Overlap Train Test: 0

# Dataset Class

In [19]:
class BreakHisDataset(Dataset):
    def __init__(self, dataframe, transform=None):
        self.df = dataframe.reset_index(drop=True)
        self.transform = transform
        
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        
        # Load image
        image = Image.open(row["path"]).convert("RGB")
        label = row["label"]
        
        # Apply transformation if any
        if self.transform:
            image = self.transform(image)
            
        return image, label

# Transform data

In [20]:
from torchvision import transforms

# Augmentation + Transformation Training Dataset
train_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomVerticalFlip(p=0.5),
    transforms.RandomRotation(degrees=90),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])

# Transformation only for Validation & Test
val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                        std=[0.229, 0.224, 0.225])
])

# Create Dataset Object

In [21]:
train_images = BreakHisDataset(train, transform=train_transform)
val_images = BreakHisDataset(val, transform=val_test_transform)
test_images = BreakHisDataset(test, transform=val_test_transform)

In [22]:
print(len(train_images))
print(len(val_images))
print(len(test_images))

5842
864
1077

# DataLoaders

In [23]:
from torch.utils.data import DataLoader

In [24]:
BATCH_SIZE = 32

In [28]:
train_loader = DataLoader(
    train_images,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=True
)

val_loader = DataLoader(
    val_images,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=True
)

test_loader = DataLoader(
    test_images,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=True
)

In [29]:
# Test one batch
images, labels = next(iter(train_loader))
print("Batch image shape:", images.shape)   # should be [32, 3, 224, 224]
print("Batch labels shape:", labels.shape)
print("Labels:", labels[:10])

Batch image shape: torch.Size([32, 3, 224, 224])
Batch labels shape: torch.Size([32])
Labels: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])